/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: buh (https://sketchfab.com/buh-late)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sand-soldier-outdated-98e1431914c1408f958d9c694352cc92
Title: Sand soldier (outdated)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../rifleman/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0.323, 1.24]}>
          <primitive object={nodes['������������_rootJoint']} />
          <skinnedMesh geometry={nodes['��_1_0'].geometry} material={materials.material} skeleton={nodes['��_1_0'].skeleton} />
          <skinnedMesh geometry={nodes['��_1_1'].geometry} material={materials.material_1} skeleton={nodes['��_1_1'].skeleton} />
          <skinnedMesh geometry={nodes['��_1_1_1'].geometry} material={materials.material_1} skeleton={nodes['��_1_1_1'].skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
