/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: tnnv (https://sketchfab.com/tnnv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sniper-911961c499f04440a1ad9a953df282ff
Title: Sniper
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../sniper/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_13.geometry} material={materials['Material.001']} skeleton={nodes.Object_13.skeleton} />
            <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Material} skeleton={nodes.Object_15.skeleton} />
            <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.M_LayeredMaterial} skeleton={nodes.Object_17.skeleton} />
            <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.M_LayeredMaterial} skeleton={nodes.Object_19.skeleton} />
            <skinnedMesh geometry={nodes.Object_21.geometry} material={materials['M_LayeredMaterial.001']} skeleton={nodes.Object_21.skeleton} />
            <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.ScopeGlass} skeleton={nodes.Object_22.skeleton} />
          </group>
          <mesh geometry={nodes.Bullet_M_LayeredMaterial001_0.geometry} material={materials['M_LayeredMaterial.001']} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
